services:
  - type: web
    name: task-manager-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://your-api-name.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      # SPA Route - handle all HTML requests
      - type: rewrite
        source: /(.*)(.html)$
        destination: /index.html
      # SPA Route - handle all direct navigation routes
      - type: rewrite
        source: /(.*)
        destination: /index.html 