services:
  - type: web
    name: task-manager-frontend
    runtime: static
    buildCommand: npm install && npm run build:render
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://your-api-name.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      # First handle actual static assets
      - type: rewrite
        source: /assets/(.*) 
        destination: /assets/$1
      # Then handle all other paths by directing to index.html
      - type: rewrite
        source: /(.*)
        destination: /index.html
    # Ensure any 404 routes go back to index.html (crucial for SPA routing)
    notFoundPage: index.html 